import { app, BrowserWindow, ipcMain } from 'electron';
import { SyncService } from './services/sync.service';
import { initLocalDatabase } from './services/database.service';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

app.on('ready', () => {
  initLocalDatabase(); // Lance la création des tables SQLite au démarrage
  createWindow();
});
const db = initLocalDatabase();
const syncService = new SyncService(db);

ipcMain.handle('sync:full-pull', async () => {
  try {
    await syncService.syncAll();
    return { success: true };
  } catch (error) {
    console.error('Erreur de synchro:', error);
    return { success: false, error: error.message };
  }
});

// Handler pour récupérer le staff en local
ipcMain.handle('db:get-staff-list', async () => {
  try {
    const staff = db.prepare('SELECT id, full_name, role, avatar_url FROM local_staff_cache').all();
    return staff;
  } catch (error) {
    console.error("Erreur SQLite list:", error);
    return [];
  }
});

// Handler pour vérifier le PIN
ipcMain.handle('db:check-staff-pin', async (_event, pin: string) => {
  const user = db.prepare('SELECT * FROM local_staff_cache WHERE pos_pin = ?').get(pin);
  return user || null;
});

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
